version: '3.3'

services:

  addr:
    image: rehaanmazid009/addr-service
    environment:
      - PORT=5001
    networks:
      addr_network:
        aliases:
          - addr
    deploy:
      replicas: 10
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role != manager]
      

  nginx:
    image: rehaanmazid009/addr-nginx
    ports:
      - "80:80"
    depends_on:
      - addr
    networks:
      - addr_network
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role != manager]

networks:

  addr_network:
    driver: overlay